baseURL = 'https://hexaliker.fr/'
languageCode = 'en-US'
title = "Alexis' Portfolio"
theme = "terminal"
copyright = """
Â© 2026 Alexis Lecam :: Posts licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>
"""

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"

  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  autoCover = true
  showLastUpdated = true
  readingTime = true

  subtitle = "My awesome portfolio!"
  owner = "Alexis Lecam"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other awesome posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  missingContentMessage = "Here be dragons!"
  missingBackButtonLabel = "Back to home page"
  minuteReadingTime = "minute read"
  words = "words"

[markup.goldmark.renderer]
  unsafe = true

[params.logo]
  logoText = "Alexis Lecam"
  logoHomeLink = "/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "about"
    name = ":: About Me"
    url = "/"
  [[menu.main]]
    identifier = "posts"
    name = ":: Posts"
    url = "/posts"